module.exports = {
    MAP_WIDTH: 6400,
    MAP_HEIGHT: 3600,
    PISTOL_RELOAD_TIME: 100,
    PISTOL_BULLET_SPEED: 1500,
    PLAYER_MOVEMENT_SPEED: 200,

    PLAYER_SPRITE_WIDTH: 32,
    PLAYER_SPRITE_HEIGHT: 64,

    WALL_SPRITE_WIDTH: 50,
    WALL_SPRITE_HEIGHT: 50,

    STANDARD_PROJECTILE_WIDTH: 8
};


