module.exports = {
    UPDATES_PER_SECOND: 10,

    MAP_WIDTH: 6400,
    MAP_HEIGHT: 3600,

    PISTOL_RELOAD_TIME: 400,
    PISTOL_BULLET_SPEED: 1000,
    PISTOL_BULLETS_IN_CHAMBER: 18,
    PISTOL_MAGAZINE_RELOAD_TIME: 1300,

    PISTOL_SPRITE_WIDTH: 40,
    PISTOL_SPRITE_HEIGHT: 28,

    MACHINE_GUN_RELOAD_TIME: 100,
    MACHINE_GUN_BULLET_SPEED: 700,
    MACHINE_GUN_BULLETS_IN_CHAMBER: 40,
    MACHINE_GUN_MAGAZINE_RELOAD_TIME: 1300,

    MACHINE_GUN_SPRITE_WIDTH: 57,
    MACHINE_GUN_SPRITE_HEIGHT: 27,

    PLAYER_MOVEMENT_SPEED: 200,

    PLAYER_SPRITE_WIDTH: 42,
    PLAYER_SPRITE_HEIGHT: 76,

    PLAYER_MAX_HEALTH: 220,
    TAKE_DAMAGE: 10,
    PLAYER_MIN_HEALTH: 10,

    WALL_SPRITE_WIDTH: 50,
    WALL_SPRITE_HEIGHT: 50,

    STANDARD_PROJECTILE_WIDTH: 8
};


