module.exports = {
    UPDATES_PER_SECOND: 10,

    MAP_WIDTH: 6400,
    MAP_HEIGHT: 3600,
    PISTOL_RELOAD_TIME: 400,
    PISTOL_BULLET_SPEED: 1000,
    PISTOL_BULLETS_IN_CHAMBER: 18,
    PISTOL_MAGAZINE_RELOAD_TIME: 1300,

    PLAYER_MOVEMENT_SPEED: 200,

    PLAYER_SPRITE_WIDTH: 42,
    PLAYER_SPRITE_HEIGHT: 76,

    WALL_SPRITE_WIDTH: 50,
    WALL_SPRITE_HEIGHT: 50,

    STANDARD_PROJECTILE_WIDTH: 8
};


