module.exports = {
    AGENT_UPDATES_PER_SECOND: 15,
    PROJECTILE_UPDATES_PER_SECOND: 3,
    PICKUP_UPDATES_PER_SECOND: 3,
    SCOREBOARD_UPDATE_PER_SECOND: 1,
    EXPLOSIVE_BARREL_UPDATE_PER_SECOND: 3,

    MAP_OBJECTS_COUNT: 45,

    INVISIBILITY_DURATION: 5, // seconds

    WEAPON_RESPAWN_RATE: 60, // seconds
    EXPLOSIVE_BARREL_RESPAWN_RATE: 60,
    MACHINE_GUNS_ON_MAP: 7,
    PISTOLS_ON_MAP: 0,
    SHOTGUNS_ON_MAP: 7,
    BAZOOKAS_ON_MAP: 4,
    EXPLOSIVE_BARRELS_ON_MAP: 15,

    MAP_WIDTH: 6400,
    MAP_HEIGHT: 3600,

    WINDOW_WIDTH: 1280,
    WINDOW_HEIGHT: 720,

    PISTOL_RELOAD_TIME: 400,
    PISTOL_BULLET_SPEED: 1000,
    PISTOL_BULLETS_IN_CHAMBER: 18,
    PISTOL_MAGAZINE_RELOAD_TIME: 1300,
    PISTOL_PROJECTILE_DAMAGE: 70,

    PISTOL_SPRITE_WIDTH: 40,
    PISTOL_SPRITE_HEIGHT: 28,

    MACHINE_GUN_RELOAD_TIME: 100,
    MACHINE_GUN_BULLET_SPEED: 1200,
    MACHINE_GUN_BULLETS_IN_CHAMBER: 40,
    MACHINE_GUN_MAGAZINE_RELOAD_TIME: 1300,
    MACHINE_GUN_PROJECTILE_DAMAGE: 50,

    MACHINE_GUN_SPRITE_WIDTH: 57,
    MACHINE_GUN_SPRITE_HEIGHT: 27,

    SHOTGUN_RELOAD_TIME: 550,
    SHOTGUN_BULLET_SPEED: 700,
    SHOTGUN_BULLETS_IN_CHAMBER: 10,
    SHOTGUN_MAGAZINE_RELOAD_TIME: 1300,
    SHOTGUN_PROJECTILE_DAMAGE: 25,

    SHOTGUN_SPRITE_WIDTH: 45,
    SHOTGUN_SPRITE_HEIGHT: 30,

    BAZOOKA_RELOAD_TIME: 1000,
    BAZOOKA_BULLET_SPEED: 650,
    BAZOOKA_BULLETS_IN_CHAMBER: 3,
    BAZOOKA_MAGAZINE_RELOAD_TIME: 1300,

    BAZOOKA_SPRITE_WIDTH: 50,
    BAZOOKA_SPRTE_HEIGHT: 30,

    BAZOOKA_EXPLOSION_SIZE: 256,
    BAZOOKA_EXPLOSION_DAMAGE: 250,

    PLAYER_MOVEMENT_SPEED: 200,

    PLAYER_SPRITE_WIDTH: 56,
    PLAYER_SPRITE_HEIGHT: 65,

    PLAYER_MAX_HEALTH: 220,
    TAKE_DAMAGE: 100,
    PLAYER_MIN_HEALTH: 100,

    WALL_SPRITE_WIDTH: 50,
    WALL_SPRITE_HEIGHT: 50,
    EXPLOSIVE_BARREL_SPRITE_WIDTH: 38,
    EXPLOSIVE_BARREL_SPRITE_HEIGHT: 64,
    STANDARD_PROJECTILE_WIDTH: 14,
    BAZOOKA_PROJECTILE_WIDTH: 28,

    ZONE_SIZE: 100
};


