package com.mygdx.game.settings

const val ZONE_SIZE = 100

const val WINDOW_WIDTH = 1280f
const val WINDOW_HEIGHT = 720f

const val MAP_WIDTH = 6400
const val MAP_HEIGHT = 3600

const val PISTOL_RELOAD_TIME = 400L
const val PISTOL_BULLET_SPEED = 1000f
const val PISTOL_BULLETS_IN_CHAMBER = 18

const val PISTOL_SPRITE_WIDTH = 40f
const val PISTOL_SPRITE_HEIGHT = 28f

const val MACHINE_FUN_RELOAD_TIME = 100L
const val MACHINE_GUN_BULLET_SPEED = 700f
const val MACHINE_GUN_BULLETS_IN_CHAMBER = 40

const val MACHINE_GUN_SPRITE_WIDTH = 57f
const val MACHINE_GUN_SPRITE_HEIGHT = 27f

const val PLAYER_MOVEMENT_SPEED = 200

const val PLAYER_SPRITE_WIDTH = 42f
const val PLAYER_SPRITE_HEIGHT = 76f

const val HEALTH_BAR_SPRITE_HEIGHT = -16f
const val PLAYER_MAX_HEALTH = 220f

const val WALL_SPRITE_WIDTH = 50f
const val WALL_SPRITE_HEIGHT = 50f

const val STANDARD_PROJECTILE_WIDTH = 8f

const val GROUND_TEXTURE_WIDTH = 250f
const val GROUND_TEXTURE_HEIGHT = 250f

